#!/usr/bin/env bash

set -e

function showhelp() {
  echo "Usage: cluster ibft [{command}] [{flags}]"
  echo "Consensus:"
  echo "  ibft            Start local test environment with IBFT consensus"
  echo "Commands:"
  echo "  stop            Stop the running Docker environment"
  echo "  destroy         Destroy the running Docker environment"
  echo "  write-logs      Write validator STDOUT/STDERR to log files (non-Docker mode)"
  echo "Flags:"
  echo "  --docker        Run using Docker (requires docker-compose)."
  echo "  --help          Display this help information"
}

function initIbftConsensus() {
  ./xgrchain secrets init --insecure --data-dir test-chain- --num 4

  node1_id=$(./xgrchain secrets output --data-dir test-chain-1 | grep Node | head -n 1 | awk -F ' ' '{print $4}')
  node2_id=$(./xgrchain secrets output --data-dir test-chain-2 | grep Node | head -n 1 | awk -F ' ' '{print $4}')

  genesis_params="--consensus ibft --validators-prefix test-chain- \
    --bootnode /ip4/127.0.0.1/tcp/30301/p2p/$node1_id \
    --bootnode /ip4/127.0.0.1/tcp/30302/p2p/$node2_id"
}

function createGenesis() {
  ./xgrchain genesis $genesis_params \
    --block-gas-limit 10000000 \
    --premine 0x85da99c8a7c2c95964c8efd687e95e632fc533d6:1000000000000000000000 \
    --premine 0x0000000000000000000000000000000000000000 \
    --epoch-size 10
}

function startNodes() {
  if [ "$1" == "write-logs" ]; then
    echo "Writing validators logs to files..."
  fi

  for i in {1..4}; do
    data_dir="./test-chain-$i"
    grpc_port=$((10000 * $i))
    libp2p_port=$((30300 + $i))
    jsonrpc_port=$((10000 * $i + 2))
    log_file="./validator-$i.log"

    if [ "$1" == "write-logs" ]; then
      touch "$log_file"
      ./xgrchain server --data-dir "$data_dir" --chain genesis.json \
        --grpc-address ":$grpc_port" --libp2p ":$libp2p_port" --jsonrpc ":$jsonrpc_port" \
        --num-block-confirmations 2 --log-level DEBUG 2>&1 | tee "$log_file" &
    else
      ./xgrchain server --data-dir "$data_dir" --chain genesis.json \
        --grpc-address ":$grpc_port" --libp2p ":$libp2p_port" --jsonrpc ":$jsonrpc_port" \
        --num-block-confirmations 2 --log-level DEBUG &
    fi
  done

  wait
}

function startServerFromDockerCompose() {
  export EDGE_CONSENSUS="ibft"
  docker-compose -f ./docker/local/docker-compose.yml up -d --build
}

function destroyDockerEnvironment() {
  docker-compose -f ./docker/local/docker-compose.yml down -v
}

function stopDockerEnvironment() {
  docker-compose -f ./docker/local/docker-compose.yml stop
}

if [[ "$1" == "--help" ]] || [[ $# -eq 0 ]]; then
  showhelp
  exit 0
fi

if [ "$1" != "ibft" ]; then
  echo "Unsupported consensus mode. Supported mode is: ibft."
  showhelp
  exit 1
fi

if [[ "$2" == "--docker" ]] && ! command -v docker-compose >/dev/null 2>&1; then
  echo "docker-compose is not installed."
  echo "Manual installation instructions: Visit https://docs.docker.com/compose/install/ for more information."
  exit 1
fi

rm -rf test-chain-*
rm -f genesis.json

go build -o xgrchain .

case "$2" in
"--docker")
  if [ "$3" == "destroy" ]; then
    destroyDockerEnvironment
    echo "Docker environment destroyed!"
    exit 0
  elif [ "$3" == "stop" ]; then
    stopDockerEnvironment
    echo "Docker environment stopped!"
    exit 0
  fi

  echo "Running docker environment..."
  startServerFromDockerCompose
  echo "Docker environment deployed."
  ;;
*)
  initIbftConsensus
  createGenesis
  startNodes "$2"
  ;;
esac
